### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by xuetengfei** [Rouwanzi/AlfredWorkflow_YoudaoTranslate#1]
你好，我有一个小建议。
日常工作中，我给一个变量起名，但是又不是很确定我的拼写是否正确。所为，我会打开AlfredWorkflow_YoudaoTranslate 然后手动输入单词。如果正确了，那么希望按住 空格键 把刚才输入的单词到复制到剪贴板中。

**Comment by TerryX-Lee** [comment]
是这样，alfred在操作时候即使输入有了反馈，光标也是一直在的，所以空格就会输入，并且alfred本身不提供针对空格的操作。有个方式，就是用输入法，只要不是太偏的词，一般也能起到你说的这个效果，不过编码的时候切输入法确实挺令人烦躁的。
一会我发布一个新的，把源查询词加到下拉菜单的第一个，就可以直接复制了

**Comment by xuetengfei** [comment]
@Rouwanzi 太感谢了，谢谢你。
